#nexus.url=http://nrp.devpod.ir/nexus/content/repositories/IoTReleases
#nexus.username=a.keshavarz
#nexus.password=a@123456
# HTTP(S) proxy
#systemProp.http.proxyHost=127.0.0.1
#systemProp.http.proxyPort=10808
#systemProp.https.proxyHost=127.0.0.1
#systemProp.https.proxyPort=10808
#
## Don’t proxy local
#systemProp.http.nonProxyHosts=localhost|127.0.0.1
#org.gradle.java.home=~/jdk/jdk-11.0.9

#systemProp.javax.net.ssl.trustStore=/home/r.taleb/.gradle/corp-truststore.jks
#systemProp.javax.net.ssl.trustStorePassword=changeit