package org.example.jms;


import java.io.Serializable;
import java.util.UUID;

public class DiranaInputMessage implements Serializable {
	private long id; // message id in Dirana Server
	private long senderMessageId; // message id from message sender
	private String senderName; // peer name of sender (if you registered on sender peer)
	private long senderId; // peer id of sender (if you didn’t register on sender peer)
	private int type; // type of message
	private String content; // content of message
	private String address; // address of sender (if sender registered on your peer)
	private String origin; // origin of sender (if sender registered on your peer)
	private long trackerId; // tracker id of message, generated by Dirana (if message sent in sync mode (e.g. HTTP channel))

	public DiranaInputMessage(String id) {
		this.id = System.currentTimeMillis();
		this.senderMessageId = 12345678;
		this.senderName = senderName;
		this.senderId = 123456798;
		this.type = 3;
		this.content = generateDevicePayload(id);
		this.address = "loadtest";
		this.origin = "loadtest";
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getSenderMessageId() {
		return senderMessageId;
	}

	public void setSenderMessageId(long senderMessageId) {
		this.senderMessageId = senderMessageId;
	}

	public String getSenderName() {
		return senderName;
	}

	public void setSenderName(String senderName) {
		this.senderName = senderName;
	}

	public long getSenderId() {
		return senderId;
	}

	public void setSenderId(long senderId) {
		this.senderId = senderId;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getOrigin() {
		return origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	public long getTrackerId() {
		return trackerId;
	}

	public void setTrackerId(long trackerId) {
		this.trackerId = trackerId;
	}

	private String generateDevicePayload(String deviceId) {

		String payload = String.format("""
                {
                    "$requestId": "%s",
                    "deviceTwinDocument": {
                        "attributes": {
                            "reported": {
                                "temp": 10
                            }
                        }
                    }
                }
                """, deviceId);
		return payload;

	}














}
